parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '3.15'
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                type: 'annotation'
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
            # @todo register not manually here, but in a package
            OpenTraining\Registration:
                type: 'annotation'
                dir: '%kernel.project_dir%/packages/Registration/src/Entity'
                prefix: 'OpenTraining\Registration\Entity'

            OpenTraining\Provision:
                type: 'annotation'
                dir: '%kernel.project_dir%/packages/Provision/src/Entity'
                prefix: 'OpenTraining\Provision\Entity'
