easy_admin:
    entities:
        Training:
            class: 'App\Entity\Training'
            form:
                fields: ['name', 'perex', 'duration', 'capacity', 'price', 'place', 'trainer']
                # @todo how to exclude fields?
                # https://github.com/EasyCorp/EasyAdminBundle/issues/589
        TrainingTerm:
            label: 'Training Term'
            class: 'App\Entity\TrainingTerm'
        Trainer:
            class: 'App\Entity\Trainer'
            form:
                fields: ['name', 'email', 'phone', 'bio']
        Place:
            class: 'App\Entity\Place'
