sensio_framework_extra:
    router:
        annotations: false
    view:
        annotations: true
    cache:
        annotations: true
    security:
        annotations: true
    psr_message:
        enabled: false
