language: php

matrix:
  include:
    - php: 7.2

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit

  # check coding standards
  - composer check-cs

  # static analysis
  - composer phpstan

  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  - ./bin/console lint:twig templates

